name: 'Codespell'

on:
  push:
  pull_request:

jobs:
  codespell:
    name: 'â˜‘ï¸ Codespell'
    runs-on: ubuntu-latest

    steps:

    - name: 'ğŸ§° Checkout'
      uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0

    - name: 'â˜‘ï¸ Run codespell'
      uses: codespell-project/actions-codespell@master
      with:
        check_filenames: true
        check_hidden: true
        ignore_words_file: .codespellignore
